### ISSUE TITLE
[REQ]Is it better than openMP? Why my test can only reach 28% CPU, but not 100% for full threads testing?

### ISSUE THREAD

**Issue by yifan513** [bshoshany/thread-pool#33] opened 2022-01-21 20:26 UTC
As the title.
Can you do more testing or explanation in the readme file?
Thanks

**Comment by bshoshany** [comment] 2022-01-24 03:11
OpenMP can do much more. The main advantage of my library over OpenMP is that it's smaller and simpler.

The library itself only provides a way to execute tasks using a thread pool. Writing the tasks themselves in an optimized and efficient way is up to you, and it's not easy. If you don't get 100% CPU utilization, then the problem is with your code.

If you can provide a full code example that I can compile and test on my computer, I could try to find out if there is anything you can do to optimize it.

(Since this isn't an issue with the library itself, I'm closing the issue, but please feel free to continue the discussion.)

**Closed by bshoshany** 2022-01-24 03:11 UTC
Labels: enhancement

**Comment by BarabashkaD** [comment] 2022-01-24 13:46
@bshoshany  @yifan513 
I think this library have big advantage over OpenMP ....
its allow to precreate thread pool  and avoid it on the fly ...
that for short realtime tasks reduce overhead and much better that OpenMP 
also its can be allow to debug in source level

**Comment by bshoshany** [comment] 2022-01-24 16:02
@BarabashkaD glad you think so! :)

**Comment by BarabashkaD** [comment] 2022-01-24 16:14
@bshoshany Its from my experience with your predecessor [https://github.com/progschj/ThreadPool](url)
I use it in production code after long investigation of OpenMP performance 
 in addition library as your platform independed and can be used across Windows/Linux/android 
 more simple that openmp that depended on toolchain and runtime dynamic library
